#!/bin/bash

i=$1
ARG=""

while [ $i -gt 0 ]
do
        random_num="$(($RANDOM% 2000000000-1))"
        ARG="${ARG}$random_num "
        i=$(($i-1))
done

clear

echo "========================"
echo "Arguments : $ARG"
echo "========================"
./push_swap $ARG
./push_swap $ARG | wc -l

./push_swap $ARG | ./checker_Mac $ARG
